#!/usr/bin/env python

import sys
import subprocess
import os
from moviepy.editor import VideoFileClip, concatenate_videoclips

input_path = sys.argv[1]
out_path = sys.argv[2]
noise = sys.argv[3]
duration = sys.argv[4]

try:
    ease = float(sys.argv[5])
except IndexError:
    ease = 0.2

minimum_duration = 1.0

def generate_timestamps(path, noise, duration):
    command = "detect_frozen_frames {} {} {}".format(input_path, noise, duration)
    output = subprocess.run(command, shell=True, capture_output=True, text=True)
    output = output.stdout.split("\n")[:-1]
    timestamps = []
    for line in output:
        timestamps.append(line.split(": ")[1])

    return timestamps


def main():
    count = 0
    last = 0
    timestamps = generate_timestamps(input_path, noise, duration)
    print("Timestamps: {}".format(timestamps))
    video = VideoFileClip(input_path)
    full_duration = video.duration
    clips = []

    for i in range(0, len(timestamps)-1, 2):
        print("Index: ", i)
        start = float(last)
        end = float(timestamps[i+1])
        to = float(timestamps[i]) + ease

        clip_duration = float(to) - start
        # Clips less than one seconds don't seem to work
        print("Clip Duration: {} seconds".format(clip_duration))

        if clip_duration < minimum_duration:
            continue

        if full_duration - to < minimum_duration:
            continue


        print("Clip {} (Start: {}, End: {})".format(count, start, to))
        clip = video.subclip(start, to)
        clips.append(clip)
        last = end
        count += 1

    if not clips:
        print("No frozen frames detected, exiting...")
        return


    if len(timestamps) % 2 == 0 and full_duration - float(last) > minimum_duration:
        print("Clip {} (Start: {}, End: {})".format(count, last, 'EOF'))
        clips.append(video.subclip(last))
    else:
        to = timestamps[-1]
        print("Clip {} (Start: {}, End: {})".format(count, last, to))
        clips.append(video.subclip(last, to))

    processed_video = concatenate_videoclips(clips)
    processed_video.write_videofile(
        out_path,
        fps=60,
        preset='ultrafast',
        codec='libx264',
        audio_codec='aac'
    )

    video.close()


main()
